version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: qr_video_db
      MYSQL_USER: qr_user
      MYSQL_PASSWORD: qr_user_password
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"